#  Question 1:-
### A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions


### It have 2 tail-test 
### so,
+ **Null Hypothesis:** $\mu_1 = \mu_2$
+ **Alternative Hypthosis:** $\mu_1 \neq \mu_2$
### Ho: There is no significant difference in diameters of cutlets between two units
### Ha: There is significant difference in diameters of cutlets between two units

In [39]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import ttest_1samp, ttest_ind, ttest_rel

In [40]:
# Load the dataset
cutlet=pd.read_csv('Cutlets.csv')
cutlet.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [41]:
cutlet.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [42]:
unit_a= cutlet['Unit A']
unit_b= cutlet['Unit B']

In [43]:
# two independent sample 2-tail ttest
t_stats,pvalue=stats.ttest_ind(unit_a.dropna(),unit_b.dropna(),alternative='two-sided')


In [44]:
#comparing p_value with significance level 
print('P_value=',pvalue)
alpha=0.05
if pvalue<= alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

P_value= 0.4722394724599501
Fail to reject null hypothesis


## Here we accept the null hypothesis and reject alternate hypothesis

## Inference: There is no significant difference in diameters of cutlets between two units

# Question 2:-
### A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.

### Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.




In [45]:
#load the dataset
labtat=pd.read_csv('labTAT.csv')
labtat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

### Since there is 4 sample so we perform ANOVA F-statistic
### Ho: $ \mu_1=\mu_2=\mu_3=\mu_4 $ 
### Ha: Atlest one sample mean is different

In [46]:
labtat.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [47]:
lab1=labtat['Laboratory 1']
lab2=labtat['Laboratory 2']
lab3=labtat['Laboratory 3']
lab4=labtat['Laboratory 4']

In [48]:
#ANOVA f-statistic test
f_stats,p_value=stats.f_oneway(lab1,lab2,lab3,lab4)
print("F_statistic=",f_stats,"pvalue=", p_value)

F_statistic= 118.70421654401437 pvalue= 2.1156708949992414e-57


In [49]:
#compare pvalue with significant level
alpha=0.05
if p_value<= alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

Reject the null hypothesis


### Here we reject the null hypothesis and accept the alternate hypothesis i.e. atleast simple mean is difference

### Inference:- There is difference in average turn around time of report of the laboratories


# Question 3:-

### Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

###  Ho: sales of product for four different regions of male-female buyer rations are similar across regions
###  Ha:sales of product for four different regions of male-female buyer rations are not similar across regions


In [50]:
buyer_data=pd.read_csv('BuyerRatio.csv')
buyer_data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [51]:
#droping Observed value coloum
buyer=buyer_data.drop(['Observed Values'],axis=1)
buyer

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [52]:
male=pd.Series(buyer.iloc[0,0:]).values
male

array([ 50, 142, 131,  70], dtype=int64)

In [53]:
female=pd.Series(buyer.iloc[1,0:]).values
female

array([ 435, 1523, 1356,  750], dtype=int64)

In [73]:
observed=[male,female]
observed

[array([ 50, 142, 131,  70], dtype=int64),
 array([ 435, 1523, 1356,  750], dtype=int64)]

In [55]:
# chi-squared implementation
stat, p, dof, expected = stats.chi2_contingency(data)
stat,p,dof,expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [76]:
#compare pvalue with significant level
alpha=0.05
if p<= alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis


### Therefor, we accept the null hypothesis 
### Inference:- Proportions of male and female across all regions are same

# Question 4:-
### TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

### HO : the defective % do not varies by centre
### Ha : the defective % varies by centre

In [58]:
#Load dataset
customer_form=pd.read_csv('Costomer+OrderForm.csv')
customer_form

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [72]:
#counting the Error free and defective data
data=customer_form.Phillippines.value_counts(),customer_form.Indonesia.value_counts(),customer_form.Malta.value_counts(),customer_form.India.value_counts()
data

(Error Free    271
 Defective      29
 Name: Phillippines, dtype: int64,
 Error Free    267
 Defective      33
 Name: Indonesia, dtype: int64,
 Error Free    269
 Defective      31
 Name: Malta, dtype: int64,
 Error Free    280
 Defective      20
 Name: India, dtype: int64)

In [91]:
# contingency table
data_table = [[271,267,269,280],
[29,33,31,20]]
data_table

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [92]:
# Execute chi-squared 
stat, p_val, dof, expected = stats.chi2_contingency(data_table)
stat, p_val, dof, expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [90]:
#compare pvalue with significant level
alpha=0.05
if p_val<= alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

Fail to reject null hypothesis


### Hence we accept the null hypothesis 
### Inference:- The defective % do not varies significantly by centre